### PR TITLE
Remove `email`, `address`

### LINKED ISSUE #120: Remove `Email` and `Address` fields

### PR DESCRIPTION
**Pull request by kiatkat**
Resolves #120.

### CODE REVIEW

**Review by eyelessrhyme7 — COMMENTED** [review]
LGTM

**Review by jack1e0 — APPROVED** [review]
lgtmss

**Review by yarnmengnus — APPROVED** [review]
LGTM

**Review by newway1814 — APPROVED** [review]
Good Job on the removal task!!

**Pull request merged**
