### PR TITLE
Miscellaneous changes

### PR DESCRIPTION
**Pull request by kiatkat**
- Update DG
- Update PPP
- Fix bug

### CODE REVIEW

**Review by eyelessrhyme7 — APPROVED** [review]
LGTM!

**Review by newway1814 — APPROVED** [review]
LGTM!

**Review by jack1e0 — APPROVED** [review]
LTGMM

**Review by yarnmengnus — APPROVED** [review]

**Comment by yarnmengnus** [comment]
LGTM

**Pull request merged**
